### ISSUE TITLE
 a question about package functionality

### ISSUE THREAD

**Issue by aparneshgaurav** [cloudyr/aws.comprehend#27]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [x] a question about package functionality
 - [ ] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

 - [a fully reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) using a publicly available dataset (or provide your data)
 - if an error is occurring, include the output of `traceback()` run immediately after the error occurs
 - the output of `sessionInfo()`

Put your code here:

```R
## load package
library("aws.comprehend")

## code goes here


## session info for your system
sessionInfo()
```

**Comment by aparneshgaurav** [comment]
Is this package free to use under cloudyr . Or will it get billed as per AWS comprehend payment policies ? Thanks .

**Comment by MarkEdmondson1234** [comment]
No, you pay for your own usage.
