### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by missaugustina** [cloudyr/aws.comprehend#3]
If this is one of the packages you're looking for a maintainer for then I'd love to help!

**Comment by leeper** [comment]
Awesome! I think this is mostly in a good state, so it should be pretty trivial to take over.

**Comment by missaugustina** [comment]
I'll spend some time on issues tomorrow (in addition to the other pkgs I volunteered for) and see if they are current.

**Comment by leeper** [comment]
Cool - the kind of lurking big issue on all of these packages is that they don't have automatically executed test suites. So, while the APIs they wrap are mostly stable, there's a chance something can go off the rails and it wouldn't be immediately obvious. Just something to be aware of as you start poking around! Thanks again for volunteering - I'll add you to the org and then let's prioritize where you want to get started.

**Comment by missaugustina** [comment]
I added unit test w/ mocking to MeetupR & can do similar here. I had proposed integration tests for merges via Travis which can also be periodically triggered, but hadn't prioritized it. I'm picking that back up in MeetupR & can explore here. With new codebases I usually start with tests & docs to get familiar. Thanks a lot & looking forward to contributing!!

**Comment by leeper** [comment]
Sounds great! Thanks so much!

**Comment by MarkEdmondson1234** [comment]
Hi @missaugustina are you established as the maintainer now or does there need to be some more transfer stuff to sort out?

**Comment by antoine-sachet** [comment]
I've had 5 issues and 2 PRs waiting for approval for months so I don't think the package is active anymore.

@leeper I would be happy to start maintaining this very useful package. I already maintain several packages for work so it's no biggie. 

AWS comprehend has added new features that I am keen to integrate. It would also be cool to integrate with AWS translate as well! Technically it is not part of AWS comprehend but it would be very convenient to have both side by side.

**Comment by MarkEdmondson1234** [comment]
@antoine-sachet  I have just added you to the team if you accept :)

If anyone else would like to maintain as well (@missaugustina ) let me know.

**Comment by antoine-sachet** [comment]
I am now maintaining this package but I invite anyone wanting to get involved to reach out.
