### ISSUE TITLE
Comprehend Medical

### ISSUE THREAD

**Issue by dkincaid** [cloudyr/aws.comprehend#4]
Today AWS announced the availability of an add-on service for Comprehend that is focused on medical documents. They are calling it Comprehend Medical. As far as I can tell at this point it has a new service name `comprehendmedical` but uses the same data structures as the base Comprehend service. 

Would this be something to add into this package (`aws.comprehend`) or would it go into its own cloudyr R package? I'll probably start bolting it into here for now in a fork since we really want to start testing it.

**Comment by lhwostow001** [comment]
Any updates to report?

**Comment by antoine-sachet** [comment]
If the data structures are the same and it really is just an endpoint change, it would make sense to integrate `comprehendmdeical` within `aws.comprehend`. Could be via a boolean argument `medical`, via a global `option` or via an environment variable.
